services:

  db:
    image: mariadb:latest
    restart: always
    command: --default-time-zone="+07:00"
    environment:
      TZ: Asia/Bangkok
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smartbag_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: '1234'
    volumes:
      - db_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

  mqtt:
    image: eclipse-mosquitto:latest
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Bangkok
    depends_on:
      - db
      - mqtt

  phpmyadmin:
    image: phpmyadmin:5.2-apache
    restart: always
    ports:
      - "8080:80"
    environment:
      - TZ=Asia/Bangkok
      - PMA_HOST=db
      - PMA_USER=admin
      - PMA_PASSWORD=1234
    depends_on:
      - db

  nginx:                     # ✅ ย้ายเข้ามาใต้ services แล้ว
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./react_nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/app/dist
    depends_on:
      - app
      - mqtt

volumes:
  db_data:
