# --- HTTPS หลัก ---
server {
    listen 443 ssl;
    server_name smartbag.cloud;

    ssl_certificate /etc/letsencrypt/live/smartbag.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/smartbag.cloud/privkey.pem;

    # React Frontend
    location / {
        proxy_pass http://app:3000/;
        include /etc/nginx/proxy_params;
    }

    # API Node
    location /api {
        proxy_pass http://node-app:3000;
        include /etc/nginx/proxy_params;
    }

    # phpmyadmin
    location /phpmyadmin {
        proxy_pass http://phpmyadmin/;
        include /etc/nginx/proxy_params;
    }

    # ✅ MQTT WebSocket (จุดสำคัญ!)
    location /mqtt {
        proxy_pass http://mqtt:9001;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;

        proxy_read_timeout 86400;
    }
}

# Redirect HTTP → HTTPS
server {
    listen 80;
    server_name smartbag.cloud;
    return 301 https://$host$request_uri;
}
